use serde::{Deserialize, Serialize};

pub mod create;
pub mod get;

/// API Object: https://www.zabbix.com/documentation/6.0/en/manual/api/reference/trigger/object
#[derive(Deserialize, Clone, Debug)]
pub struct ZabbixTrigger {
    /// ID of the trigger.
    #[serde(alias = "triggerid")]
    pub trigger_id: String,

    /// Event name generated by the trigger.
    pub event_name: String,

    /// URL associated with the trigger.
    pub url: String,

    /// Name of the trigger (required).
    pub description: String,

    /// Reduced trigger expression (required).
    pub expression: String,

    /// Severity of the trigger.
    ///
    /// Possible values are:
    ///
    /// 0 - (default) not classified;
    ///
    /// 1 - information;
    ///
    /// 2 - warning;
    ///
    /// 3 - average;
    ///
    /// 4 - high;
    ///
    /// 5 - disaster.
    pub priority: u8,

    /// OK event generation mode.
    ///
    /// Possible values are:
    ///
    /// 0 - (default) Expression;
    ///
    /// 1 - Recovery expression;
    ///
    /// 2 - None.
    pub recovery_mode: u8,

    /// Reduced trigger recovery expression.
    pub recovery_expression: String
}

/// API Object: https://www.zabbix.com/documentation/6.0/en/manual/api/reference/trigger/object#trigger-tag
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ZabbixTriggerTag {
    pub tag: String,
    pub value: String,
}